update 121 with cn proxy

diff --git a/cu121/Dockerfile b/cu121/Dockerfile
--- a/cu121/Dockerfile
+++ b/cu121/Dockerfile
@@ -1,123 +1,169 @@
 ################################################################################
 # Dockerfile that builds 'yanwk/comfyui-boot:cu121'
 # A runtime environment for https://github.com/comfyanonymous/ComfyUI
-# Using CUDA 12.1& Python 3.11
+# Using CUDA 12.1 & Python 3.12
 ################################################################################
 
 FROM opensuse/tumbleweed:latest
 
-LABEL maintainer="code@yanwk.fun"
+LABEL maintainer="YAN Wenkun <code@yanwk.fun>"
 
-# Note: GCC for InsightFace;
-#       FFmpeg for video (pip[imageio-ffmpeg] will use system FFmpeg instead of bundled).
-# Note: CMake may use different version of Python. Using 'update-alternatives' to ensure default version.
+RUN set -eu
+
+################################################################################
+# Configure to use Chinese mirrors and install Python and tools
+
 RUN --mount=type=cache,target=/var/cache/zypp \
-    set -eu \
+    zypper modifyrepo --disable --all \
+    && zypper addrepo --check --refresh --gpgcheck \
+        'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/oss/' mirror-oss \
+    && zypper addrepo --check --refresh --gpgcheck \
+        'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/non-oss/' mirror-non-oss \
     && zypper addrepo --check --refresh --priority 90 \
-        'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/Essentials/' packman-essentials \
+        'https://mirrors.tuna.tsinghua.edu.cn/packman/suse/openSUSE_Tumbleweed/Essentials/' mirror-packman-essentials \
     && zypper --gpg-auto-import-keys \
-            install --no-confirm \
-        python311 python311-pip python311-wheel python311-setuptools \
-        python311-devel python311-Cython gcc-c++ python311-py-build-cmake \
-        python311-numpy python311-opencv \
-        python311-ffmpeg-python ffmpeg x264 x265 \
-        python311-dbm \
-        google-noto-sans-fonts google-noto-sans-cjk-fonts google-noto-coloremoji-fonts \
-        shadow git aria2 \
-        Mesa-libGL1 libgthread-2_0-0 \
-    && rm /usr/lib64/python3.11/EXTERNALLY-MANAGED \
-    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 100
+        install --no-confirm --auto-agree-with-licenses \
+python312-devel \
+python312-pip \
+python312-wheel \
+python312-setuptools \
+python312-Cython \
+python312-py-build-cmake \
+python312-aiohttp \
+python312-dbm \
+python312-ffmpeg-python \
+python312-GitPython \
+python312-httpx \
+python312-joblib \
+python312-lark \
+python312-matplotlib \
+python312-mpmath \
+python312-numba-devel \
+python312-numpy \
+python312-onnx \
+python312-opencv \
+python312-pandas \
+python312-qrcode \
+python312-rich \
+python312-scikit-build \
+python312-scikit-build-core-pyproject \
+python312-scikit-image \
+python312-scikit-learn \
+python312-scipy \
+python312-svglib \
+python312-tqdm \
+Mesa-libGL1 \
+Mesa-libEGL-devel \
+libgthread-2_0-0 \
+make \
+ninja \
+git \
+aria2 \
+fish \
+fd \
+vim \
+opencv \
+opencv-devel \
+ffmpeg \
+x264 \
+x265 \
+google-noto-sans-fonts \
+google-noto-sans-cjk-fonts \
+google-noto-coloremoji-fonts \
+    && rm /usr/lib64/python3.12/EXTERNALLY-MANAGED \
+    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 100
 
-RUN --mount=type=cache,target=/root/.cache/pip \
-    pip install --break-system-packages \
-        --upgrade pip wheel setuptools
+################################################################################
+# GCC 13 
+# Compatible with CUDA 12.1
 
-# Install xFormers (stable version, will specify PyTorch version),
-# and Torchvision + Torchaudio (will downgrade to match xFormers' PyTorch version).
+RUN --mount=type=cache,target=/var/cache/zypp \
+    zypper --gpg-auto-import-keys \
+        install --no-confirm --auto-agree-with-licenses \
+gcc13 \
+gcc13-c++ \
+cpp13 \
+    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-13 90 \
+    && update-alternatives --install /usr/bin/cc  cc  /usr/bin/gcc-13 90 \
+    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-13 90 \
+    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 90 \
+    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 90 \
+    && update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-13 90 \
+    && update-alternatives --install /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-13 90 \
+    && update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-13 90 \
+    && update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 90 \
+    && update-alternatives --install /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-13 90 \
+    && update-alternatives --install /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-13 90 
+
+################################################################################
+# Configure to use Chinese mirrors, install Python packages
+
+ENV PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
+
+# PyTorch, xFormers
 RUN --mount=type=cache,target=/root/.cache/pip \
-    pip install --break-system-packages \
+    pip list \
+    && pip install \
+        --upgrade pip wheel setuptools \
+    && pip install \
         xformers torchvision torchaudio \
         --index-url https://download.pytorch.org/whl/cu121 \
-        --extra-index-url https://pypi.org/simple
+        --extra-index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
 
-# Dependencies for frequently-used
-# (Do this firstly so PIP won't be solving too many deps at one time)
-RUN --mount=type=cache,target=/root/.cache/pip \
-    pip install --break-system-packages \
-        -r https://raw.githubusercontent.com/comfyanonymous/ComfyUI/master/requirements.txt \
-        -r https://raw.githubusercontent.com/crystian/ComfyUI-Crystools/main/requirements.txt \
-        -r https://raw.githubusercontent.com/cubiq/ComfyUI_essentials/main/requirements.txt \
-        -r https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/requirements.txt \
-        -r https://raw.githubusercontent.com/jags111/efficiency-nodes-comfyui/main/requirements.txt \
-        -r https://raw.githubusercontent.com/ltdrdata/ComfyUI-Impact-Pack/Main/requirements.txt \
-        -r https://raw.githubusercontent.com/ltdrdata/ComfyUI-Impact-Subpack/main/requirements.txt \
-        -r https://raw.githubusercontent.com/ltdrdata/ComfyUI-Inspire-Pack/main/requirements.txt \
-        -r https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/requirements.txt
+# Bind environment variables (dependency library .so files)
+ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}\
+:/usr/local/lib64/python3.12/site-packages/torch/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cuda_cupti/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cuda_runtime/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cudnn/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cufft/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cublas/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cuda_nvrtc/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/curand/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cusolver/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/cusparse/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/nccl/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/nvjitlink/lib\
+:/usr/local/lib/python3.12/site-packages/nvidia/nvtx/lib"
 
-# Dependencies for more, with few hand-pick:
-# 'cupy-cuda12x' for Frame Interpolation
-# 'compel lark' for smZNodes
-# 'torchdiffeq' for DepthFM
-# 'fairscale' for APISR
-RUN --mount=type=cache,target=/root/.cache/pip \
-    pip install --break-system-packages \
-        -r https://raw.githubusercontent.com/cubiq/ComfyUI_FaceAnalysis/main/requirements.txt \
-        -r https://raw.githubusercontent.com/cubiq/ComfyUI_InstantID/main/requirements.txt \
-        -r https://raw.githubusercontent.com/Fannovel16/ComfyUI-Frame-Interpolation/main/requirements-no-cupy.txt \
-        cupy-cuda12x \
-        -r https://raw.githubusercontent.com/FizzleDorf/ComfyUI_FizzNodes/main/requirements.txt \
-        -r https://raw.githubusercontent.com/kijai/ComfyUI-KJNodes/main/requirements.txt \
-        -r https://raw.githubusercontent.com/melMass/comfy_mtb/main/requirements.txt \
-        -r https://raw.githubusercontent.com/MrForExample/ComfyUI-3D-Pack/main/requirements.txt \
-        -r https://raw.githubusercontent.com/storyicon/comfyui_segment_anything/main/requirements.txt \
-        -r https://raw.githubusercontent.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/main/requirements.txt \
-        compel lark torchdiffeq fairscale \
-        python-ffmpeg
+COPY builder-scripts/.  /builder-scripts/
 
-# 1. Fix ONNX Runtime "missing CUDA provider". Also add support for CUDA 12.1.
-#    Ref: https://onnxruntime.ai/docs/install/
-# 2. Fix MediaPipe's broken dep (protobuf<4).
+# 1. Install dependencies for ComfyUI and extensions
+# 2. Handle ONNX Runtime error "missing CUDA provider" and add CUDA 12 support, refer to: https://onnxruntime.ai/docs/install/
+# 3. Handle MediaPipe's dependency error (requires protobuf<4)
 RUN --mount=type=cache,target=/root/.cache/pip \
-    pip uninstall --break-system-packages --yes \
+    pip install \
+        -r /builder-scripts/pak3.txt \
+    && pip install \
+        -r /builder-scripts/pak5.txt \
+    && pip install \
+        -r /builder-scripts/pak7.txt \
+    && pip uninstall --break-system-packages --yes \
         onnxruntime-gpu \
     && pip --no-cache-dir install --break-system-packages \
         onnxruntime-gpu \
         --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ \
-        --extra-index-url https://pypi.org/simple \
-    && pip install --break-system-packages \
-        mediapipe
+        --extra-index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple \
+    && pip install \
+        mediapipe \
+    && pip list
 
-# Fix for libs (.so files)
-ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}\
-:/usr/local/lib64/python3.11/site-packages/torch/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cuda_cupti/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cuda_runtime/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cudnn/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cufft/lib"
+################################################################################
 
-# More libs (not necessary, just in case)
-ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}\
-:/usr/local/lib/python3.11/site-packages/nvidia/cublas/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cuda_nvrtc/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/curand/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cusolver/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/cusparse/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/nccl/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/nvjitlink/lib\
-:/usr/local/lib/python3.11/site-packages/nvidia/nvtx/lib"
+# Use Chinese mirror for HuggingFace
 
-# Create a low-privilege user
-RUN printf 'CREATE_MAIL_SPOOL=no' >> /etc/default/useradd \
-    && mkdir -p /home/runner /home/scripts \
-    && groupadd runner \
-    && useradd runner -g runner -d /home/runner \
-    && chown runner:runner /home/runner /home/scripts
+ENV HF_ENDPOINT=https://hf-mirror.com
 
-COPY --chown=runner:runner scripts/. /home/scripts/
+################################################################################
 
-USER runner:runner
-VOLUME /home/runner
-WORKDIR /home/runner
+RUN du -ah /root \
+    && find /root/ -mindepth 1 -delete
+
+COPY scripts/.  /scripts/
+
+USER root
+VOLUME /root
+WORKDIR /root
 EXPOSE 8188
 ENV CLI_ARGS=""
-CMD ["bash","/home/scripts/entrypoint.sh"]
+CMD ["bash","/scripts/entrypoint.sh"]
